# Dependencies
#markdown:            redcarpet
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Ryan Stutsman
tagline:             ''

# unused - used to be in the sidebar
description:         ''
url:                 http://rstutsman.github.io
baseurl:             ''
paginate:            5
paginate_path:       "blog/page:num/"

# About/contact
author:
  name:              Ryan Stutsman
  url:               https://twitter.com/rstutsman
  email:             stutsman@cs.utah.edu

# Custom vars
version:             1.0.0
