# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             ''
description:         ''
url:                 http://rstutsman.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Ryan Stutsman
  url:               https://twitter.com/rstutsman
  email:             stutsman@cs.utah.edu

# Custom vars
version:             1.0.0
